version: '3.8'

services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.cache
      - /app/dist
    ports:
      - "${PORT:-3005}:3005"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
      - VITE_SOLANA_NETWORK=${VITE_SOLANA_NETWORK:-devnet}
      - VITE_DRIFT_PROGRAM_ID=${VITE_DRIFT_PROGRAM_ID:-dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH}
      - VITE_SOLANA_RPC_URL=${VITE_SOLANA_RPC_URL:-https://api.devnet.solana.com}
      - VITE_USE_SSL=${VITE_USE_SSL:-false}
    command: npm run dev -- --host 0.0.0.0 --port 3005
    networks:
      - wealthbot-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3005"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    user: "1001:1001"

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT:-80}:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${PROD_API_URL:-http://api.wealthbot.com}
    networks:
      - wealthbot-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    user: "1001:1001"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  wealthbot-network:
    driver: bridge
    name: wealthbot-network
    ipam:
      driver: default
      config:
        - s