version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.vite
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - VITE_SOLANA_NETWORK=devnet
      - VITE_USE_SSL=true
      - SSL_CRT_FILE=/app/certificates/cert.pem
      - SSL_KEY_FILE=/app/certificates/key.pem
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3001"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s